CREATE TABLE artworks (
    id                      SERIAL      PRIMARY KEY,
    title                   VARCHAR     NOT NULL,
    year                    SMALLINT,
    middle_name             VARCHAR,
    org_name                VARCHAR,
    phone                   VARCHAR,
    email                   VARCHAR,
    password                VARCHAR,
    mailing_address_line_1  VARCHAR,
    mailing_address_line_2  VARCHAR,
    mailing_address_city    VARCHAR,
    mailing_address_state   VARCHAR,
    mailing_address_zip     VARCHAR,
    mailing_address_country VARCHAR,
    billing_address_line_1  VARCHAR,
    billing_address_line_2  VARCHAR,
    billing_address_city    VARCHAR,
    billing_address_state   VARCHAR,
    billing_address_zip     VARCHAR,
    billing_address_country VARCHAR
);